// Inventory
export const SET_INVENTORY = 'SET_INVENTORY';
export const CREATE_INVENTORY = 'CREATE_INVENTORY';
export const READ_INVENTORY = 'READ_INVENTORY';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const DELETE_INVENTORY = 'DELETE_INVENTORY';

// Warehouse
export const CREATE_WAREHOUSE = 'CREATE_WAREHOUSE';
export const READ_WAREHOUSES = 'READ_WAREHOUSES';
